@hackathon_HostAddress = http://localhost:5296

POST {{hackathon_HostAddress}}/simulacoes/
Accept: application/json

{
    "valorDesejado":"900.00",
    "prazo":"5"
}

###

GET {{hackathon_HostAddress}}/simulacoes?pagina=1&qtdRegistrosPagina=200
Accept: application/json

###

GET {{hackathon_HostAddress}}/produtos?dataReferencia=2025-08-20
Accept: application/json

###

### Teste de Telemetria
GET {{hackathon_HostAddress}}/telemetria

### Teste de Telemetria com data específica
GET {{hackathon_HostAddress}}/telemetria?dataReferencia=2025-01-27

### Teste de Simulação (para gerar dados de telemetria)
POST {{hackathon_HostAddress}}/simulacoes
Content-Type: application/json

{
    "valorDesejado": 10000,
    "codigoProduto": 1
}

### Teste de Produtos (para gerar dados de telemetria)
GET {{hackathon_HostAddress}}/Produtos